config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :town_halls, controllers: { sessions: 'town_halls/sessions', passwords: 'town_halls/passwords', registrations: 'town_halls/registrations', confirmations: 'town_halls/confirmations' }
  resources :manage_registration_town_halls, only: [:new, :create]
  resources :town_halls, only: [:show]
  
  root 'static_pages#welcome'
  get 'static_pages/contact', to: 'static_pages#contact'

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :villagers, only: [:show, :edit, :update] do
    resources :associate_villagers, only: [:new, :create]

    resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
    end
  end

  resources :villages do
    resources :validation_town_halls, only: [:create, :destroy]
    resources :forums do
      resources :forums_posts do
        resources :forums_posts_comments, except: [:index, :show]
      end
    end
  end

  resources :events do
    resources :attendances, only: [:new, :show, :create, :destroy]
    resources :charges, only: [:new, :create]

    resources :comments do
      resources :likes
    end

  end

  resources :offers do
    get 'offers/search', to: 'offers#search'
    resources :offers_comments
  end

  resources :categories, except: [:index, :show]



end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :offers
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :villager
    belongs_to :event
    
    has_many :likes, dependent: :destroy
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, class_name: "Villager"
    belongs_to :receiver, class_name: "Villager"
    has_many :messages, dependent: :destroy

    validates_uniqueness_of :sender_id, scope: :receiver_id

    scope :between, -> (sender_id,receiver_id) do
        where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
    end

    def recipient(current_user)
        self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
        self.messages.where("villager_id != ? AND read = ?", current_user.id, false).count
    end

  end

app/models/event.rb
class Event < ApplicationRecord
    before_create :start_date_not_before_time_now

    has_one_attached :event_picture
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances
    belongs_to :village
   

	validates :start_date, presence: true 
    validate :start_date_not_before_time_now
    validates :duration, presence: true, :numericality => { greater_than: 0 }
    validate :duration_minutes 
	validates :title, presence: true, length: { in: 3..300, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 3..1000, message: "Un description fait entre 10 et 1000 caractères" }
	validates :price, presence: true 
	validates :location, presence: true 


    def self.search(search, search_zipcode)
        @results = []
        @search = self.where("title ILIKE ?", "%#{search}%").or(self.where("description ILIKE ?", "%#{search}%"))
        @search.each { |s| @results << s if s.village.zipcode.include? search_zipcode }
        results = @results
    end

	def start_date_not_before_time_now #Méthode pour ne pas entrer une date antérieur à la date de debut 
	    if self.start_date < Date.today
            errors.add(:start_date, "la date ne doit pas etre dans le passé")
        end  
    end

    def duration_minutes #met l'entre de duree de l'event en positif
        unless duration.present? && duration > 0
            errors.add(:duration, "la durée doit etre positive")
        end
     end
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :village
  has_many :forum_posts
  
  validates :title, presence: true, length: { in: 2..40 }

  def self.initialization(village)
    self.create(title: "Forum principal", village: village) if !village.id.nil?
  end
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
    belongs_to :forum
    belongs_to :villager

    has_many :forum_post_comments

    validates :content, presence: true, length: { in: 1..400 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :villager
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :villager

  validates_presence_of :body, :conversation_id, :villager_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
    
end

app/models/offer.rb
class Offer < ApplicationRecord
    has_one_attached :offer_picture
    belongs_to :village
    belongs_to :category, optional: true
    has_many :offer_comments

	validates :title, presence: true, length: { in: 3..400, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 10..10000, message: "Un description fait entre 10 et 1000 caractères" }

    def self.search(search, search_zipcode  )
        @results = []
        @search = self.where("title ILIKE ?", "%#{search}%").or(self.where("description ILIKE ?", "%#{search}%"))
        @search.each { |s| @results << s if s.village.zipcode.include? search_zipcode }
        results = @results
    end
end

app/models/offer_comment.rb
class OfferComment < ApplicationRecord
    belongs_to :villager
    belongs_to :offer
end

app/models/role.rb
class Role < ApplicationRecord

  end

app/models/town_hall.rb
class TownHall < ApplicationRecord
  has_one :village
  has_many :forums, through: :village

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances 
  has_many :user_roles
  has_many :roles, through: :user_roles

  # Lien avec la table villager (page profil)
  has_one :villager, dependent: :destroy
  has_one :village, through: :villager

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
         
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
    belongs_to :user
    belongs_to :role
end

app/models/village.rb
class Village < ApplicationRecord
    has_one :town_hall
    has_many :events
    has_one_attached :village_avatar

    has_many :forums, dependent: :destroy

    # lien avec la table villager (profils utilisateurs)
    has_many :villagers
    has_many :users, through: :villagers
    has_many :validation_town_halls

    validates :email, presence: true, uniqueness: true, length: { in: 6..50 }
    validates :name, presence: true, uniqueness: true, length: { in: 2..40 }
    validates :zipcode, presence: true, length: {is: 5 }
end

app/models/villager.rb
class Villager < ApplicationRecord
    belongs_to :user
    belongs_to :village, optional: true
    
    has_one_attached :villager_picture

    has_many :comments, dependent: :destroy
    has_many :offer_comments, dependent: :destroy

    has_many :likes, dependent: :destroy

    has_many :forum_posts, dependent: :destroy
    has_many :forum_post_comments, dependent: :destroy
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    render "/static_pages/welcome"
  end

  def contact
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<div class="container" style="margin-top:7%">

<h2 class="text-center">Contactez-nous</h2>

<div class="row"style="margin-top:4%">
  <div class="col-md-6">
      <form action="/post" method="post">
        <input class="form-control" name="Ton nom" placeholder="Nom..." /><br />
        <input class="form-control" name="Ton email" placeholder="E-mail..." /><br />
        <input class="form-control" name="Sujet" placeholder="Sujet..." /><br />
        <textarea class="form-control" name="Ton message" placeholder="Message" style="height:150px;"></textarea><br />
        <input class="btn btn-success btn-lg" type="submit" value="Envoyez" /><br /><br />
      </form>
  </div>
  <div class="col-md-6">
    <p>LA BONNE AUBERGE</p>
    <p><i class="fa fa-phone fa-1x mr-2 grey-text"></i>Téléphone:<br/>+ 03 23 45 67 89</p>
    <p><i class="fa fa-map fa-1x mr-2 grey-text"></i>Champs-sur-Tarentaine-Marchal</p>
    <p>France, FR</p><br />


  </div>
</div>

</div>

app/views/static_pages/welcome.html.erb
<!--Main Navigation-->
<header>              

    <!--Mask-->
    <div id="intro" class="view">

        <div class="mask rgba-black-strong">

            <div class="container-fluid h-100">

                <div class="row justify-content">

                    <div class="col-md-5">

                        <!-- Heading -->
                        <h2 class="display-4 font-weight-bold white-text">Donnez vie à vos villages</h2>

                        <!-- Divider -->
                        <hr class="hr-light">

                        <!-- Description -->
                        <h5 class="white-text my-3">Quand les villageois reprennent les rênes...</h5>

                        <% if !user_signed_in? && !town_hall_signed_in? %>
                            <%= link_to "Inscrivez-vous", new_user_registration_path, class: "btn btn-success"%>
                        <% elsif user_signed_in? && !current_user.villager.village %>
                            <%= link_to "Rejoignez votre village", new_villager_associate_villager_path(current_user.villager), method: :get, class:"btn btn-success" %>
                        <% elsif town_hall_signed_in? %>
                            <%= link_to "Créer un évènement", new_event_path, class:"btn btn-success", :method => :get %>
                        <% else %>
                            <%= link_to "Participer à un évènement de votre région", events_path, class:"btn btn-success", :method => :get %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/.Mask-->

</header>
      
    <!--Main layout-->
<main class="mt-5">
        <div class="container">

            <!--Section: Best Features-->
            <section id="best-features" class="text-center">

            <!-- Heading -->
            <h2 class="mb-5 font-weight-bold">La bonne auberge est une plateforme dynamique, pour les habitants et les nouveaux arrivants des villages d'un département: apportez du dynamisme à vos régions !</h2>

             <hr class="my-5">
            <!--Section: Last events-->

            <section id="events" class="text-center">

            <!-- Heading -->
            <div class="container">
            <div class="row">
                  <div class=" mt-4 mb-4 col">
                  <h2 class="mb-5 font-weight-bold">Les derniers évènements</h2>
                  <p> Venez découvrir les derniers évènements de votre région. L'occasion de faire de nouvelles rencontres et quitter son train-train quotidien. A plusieurs la fête est plus folle n'est-ce pas ?</p>
                    <% if !user_signed_in? && !town_hall_signed_in? %>
                    <%= link_to "C'est par ici que ça se passe !", new_user_registration_path, class: "btn btn-success"%>
                    <% else %>
                    <%= link_to "C'est par ici que ça se passe !", events_path, class: "btn btn-success"%>
                    <% end %>
                  </div>
  
                  <!--Grid row-->
              <div id="carouselExampleIndicators" class="carousel slide mb-4 col" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    
                        <div class="carousel-item active">
                          <img class="d-block w-100" src="https://i.imgur.com/XkPPzym.png" width="500" height="400" alt="First slide">
                          <div class="carousel-caption d-none d-md-block"><h5>Rejoignez-nous</h5></div>
                        </div>
                        <div class="carousel-item">
                          <img class="d-block w-100" src="https://i.imgur.com/1iSOIqJ.png" width="500" height="400" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                          <img class="d-block w-100" src="https://i.imgur.com/XHb6DlL.png" width="500" height="400" alt="Third slide">
                        </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
              </div>
          </div>
      </div>                

            

            
            <!--Grid row-->

        </section>
        <!--Section: last events-->

         <hr class="my-5">

        <div class="container">
        <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-4 mb-5">
                    <i class="fa fa-camera-retro fa-4x orange-text"></i>
                    <h4 class="my-4 font-weight-bold">Expérience</h4>
                    <p class="grey-text"> Proposez ou participez à des activités et des évènements dans votre région</p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-1">
                    <i class="fa fa-heart fa-4x orange-text"></i>
                    <h4 class="my-4 font-weight-bold">Opportunités</h4>
                    <p class="grey-text">Echangez sur la vie au village et les opportunités à saisir : acquisition d'un logement, création ou reprise de commerce...</p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-1">
                    <i class="fas fa-hands-helping fa-4x orange-text"></i>
                    <h4 class="my-4 font-weight-bold">Entraide</h4>
                    <p class="grey-text">Entre voisins ou villageois, partagez, discutez, proposez des services pour faire vivre la communauté. </p>
                </div>
                <!--Grid column-->

            </div>
        </div>

        <hr class="my-5">
                   
        <div class="block-don"> 
            <div class="row">
                <div class="col-lg-6 col-md-12 mb-4">

                    <div class="view overlay z-depth-1-half">
                        <img src="https://www.webgazelle.net/scripts/files/587d4fdcb21c05.87877786/picto-messagerie-interne-2-1.png" class="img-fluid" alt="", size: "400x300">
                    </div>

                    <h4 class="my-4 font-weight-bold">Messagerie</h4>
                    <p class="grey-text">Une fois inscrit vous aurez accès à notre messagerie qui permet de garder contact avec les villageois rencontrés !</p>
                    <p class="grey-text"> Ou faire de nouvelles rencontres </p>
                    <% if !user_signed_in?%>
                        <%= link_to "Accéder à ma messagerie", new_user_registration_path, class: "btn btn-success"%>
                    <% else %>
                        <%= link_to "Accéder à ma messagerie", villager_conversations_path(:villager_id), class: "btn btn-success"%>
                    <% end %>
                </div>
        <!--Grid column-->

        <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mt-2">

                    <div class="view overlay z-depth-1-half">
                        <img src="https://i.imgur.com/qe6HIfG.png" class="img-fluid" width="330" height="230" alt="">
                        
                    </div>

                    <h4 class="my-4 font-weight-bold">Projets</h4>
                    <p class="grey-text">Vous avez comme projet d’ouvrir un commerce ? </p>
                    <p class="grey-text"> C’est ici que ça se passe.</p>
                    <% if !user_signed_in? && !town_hall_signed_in? %>
                        <%= link_to "Rejoignez un projet !", new_user_registration_path, class: "btn btn-success"%>
                    <% else %>
                        <%= link_to "Rejoignez un projet !", offers_path, class: "btn btn-success"%>
                    <% end %>
                </div>         
            </div>
        </div>
        <hr class="my-5">
        <!--Grid column-->
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6 mt-3">

                <div class="view overlay z-depth-1-half">
                    
                    <i class="fas fa-users" style="color:white; font-size: 15em;"></i>
                </div>

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-sm-6 col-md-6 col-lg-6 mt-3">
                <h4 class="my-4 font-weight-bold">Forums</h4>
                <p class="grey-text">La bonne auberge est un réseau qui relie les villageois et les mairies</p>
                <p class="grey-text">Organisez la vie au village, grâce aux forums de vos mairies</p>
                <% if !user_signed_in?%>
                    <%= link_to "Rejoignez votre voisinage", new_user_registration_path, class: "btn btn-success"%>
                <% else %>
                    <%= link_to "Rejoignez votre voisinage", new_villager_associate_villager_path(current_user.villager), class: "btn btn-success"%>
                <% end %>
            </div>  
        </div>     

</main>


         