config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :town_halls, controllers: { sessions: 'town_halls/sessions', passwords: 'town_halls/passwords', registrations: 'town_halls/registrations', confirmations: 'town_halls/confirmations' }
  resources :manage_registration_town_halls, only: [:new, :create]
  resources :town_halls, only: [:show]
  
  root 'static_pages#welcome'
  get 'static_pages/contact', to: 'static_pages#contact'

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :villagers, only: [:show, :edit, :update] do
    resources :associate_villagers, only: [:new, :create]

    resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
    end
  end

  resources :villages do
    resources :validation_town_halls, only: [:create, :destroy]
    resources :forums do
      resources :forums_posts do
        resources :forums_posts_comments, except: [:index, :show]
      end
    end
  end

  resources :events do
    resources :attendances, only: [:new, :show, :create, :destroy]
    resources :charges, only: [:new, :create]

    resources :comments do
      resources :likes
    end

  end

  resources :offers do
    get 'offers/search', to: 'offers#search'
    resources :offers_comments
  end

  resources :categories, except: [:index, :show]



end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :offers
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :villager
    belongs_to :event
    
    has_many :likes, dependent: :destroy
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, class_name: "Villager"
    belongs_to :receiver, class_name: "Villager"
    has_many :messages, dependent: :destroy

    validates_uniqueness_of :sender_id, scope: :receiver_id

    scope :between, -> (sender_id,receiver_id) do
        where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
    end

    def recipient(current_user)
        self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
        self.messages.where("villager_id != ? AND read = ?", current_user.id, false).count
    end

  end

app/models/event.rb
class Event < ApplicationRecord
    before_create :start_date_not_before_time_now

    has_one_attached :event_picture
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances
    belongs_to :village
   

	validates :start_date, presence: true 
    validate :start_date_not_before_time_now
    validates :duration, presence: true, :numericality => { greater_than: 0 }
    validate :duration_minutes 
	validates :title, presence: true, length: { in: 3..300, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 3..1000, message: "Un description fait entre 10 et 1000 caractères" }
	validates :price, presence: true 
	validates :location, presence: true 


    def self.search(search, search_zipcode)
        @results = []
        @search = self.where("title ILIKE ?", "%#{search}%").or(self.where("description ILIKE ?", "%#{search}%"))
        @search.each { |s| @results << s if s.village.zipcode.include? search_zipcode }
        results = @results
    end

	def start_date_not_before_time_now #Méthode pour ne pas entrer une date antérieur à la date de debut 
	    if self.start_date < Date.today
            errors.add(:start_date, "la date ne doit pas etre dans le passé")
        end  
    end

    def duration_minutes #met l'entre de duree de l'event en positif
        unless duration.present? && duration > 0
            errors.add(:duration, "la durée doit etre positive")
        end
     end
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :village
  has_many :forum_posts
  
  validates :title, presence: true, length: { in: 2..40 }

  def self.initialization(village)
    self.create(title: "Forum principal", village: village) if !village.id.nil?
  end
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
    belongs_to :forum
    belongs_to :villager

    has_many :forum_post_comments

    validates :content, presence: true, length: { in: 1..400 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :villager
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :villager

  validates_presence_of :body, :conversation_id, :villager_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
    
end

app/models/offer.rb
class Offer < ApplicationRecord
    has_one_attached :offer_picture
    belongs_to :village
    belongs_to :category, optional: true
    has_many :offer_comments

	validates :title, presence: true, length: { in: 3..400, message: "Un titre fait entre 5 et 140 caractères" }
	validates :description, presence: true, length: { in: 10..10000, message: "Un description fait entre 10 et 1000 caractères" }

    def self.search(search, search_zipcode  )
        @results = []
        @search = self.where("title ILIKE ?", "%#{search}%").or(self.where("description ILIKE ?", "%#{search}%"))
        @search.each { |s| @results << s if s.village.zipcode.include? search_zipcode }
        results = @results
    end
end

app/models/offer_comment.rb
class OfferComment < ApplicationRecord
    belongs_to :villager
    belongs_to :offer
end

app/models/role.rb
class Role < ApplicationRecord

  end

app/models/town_hall.rb
class TownHall < ApplicationRecord
  has_one :village
  has_many :forums, through: :village

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances 
  has_many :user_roles
  has_many :roles, through: :user_roles

  # Lien avec la table villager (page profil)
  has_one :villager, dependent: :destroy
  has_one :village, through: :villager

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
         
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
    belongs_to :user
    belongs_to :role
end

app/models/village.rb
class Village < ApplicationRecord
    has_one :town_hall
    has_many :events
    has_one_attached :village_avatar

    has_many :forums, dependent: :destroy

    # lien avec la table villager (profils utilisateurs)
    has_many :villagers
    has_many :users, through: :villagers
    has_many :validation_town_halls

    validates :email, presence: true, uniqueness: true, length: { in: 6..50 }
    validates :name, presence: true, uniqueness: true, length: { in: 2..40 }
    validates :zipcode, presence: true, length: {is: 5 }
end

app/models/villager.rb
class Villager < ApplicationRecord
    belongs_to :user
    belongs_to :village, optional: true
    
    has_one_attached :villager_picture

    has_many :comments, dependent: :destroy
    has_many :offer_comments, dependent: :destroy

    has_many :likes, dependent: :destroy

    has_many :forum_posts, dependent: :destroy
    has_many :forum_post_comments, dependent: :destroy
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/shared/_card_event.html.erb
<div class="cart-event col-12 col-sm-8 col-md-6 col-lg-4 m-2">
          
    <!-- Card content -->
    <div class="card-body d-flex flex-row">
        <!-- Content -->
        <div>
        <!-- Title -->
        <%= link_to event_path(id: event.id), class:"link_to" do %>
            <h4 class="card-title font-weight-bold mb-2" style="text-transform: uppercase;"><%= event.title %></h4>
        <% end %>
        <!-- Subtitle -->
        <p class="card-text"><i class="far fa-money-bill-alt pr-2"></i> <%= event.price %> €</p>
        <p class="card-text"><i class="fas fa-map-marker-alt pr-2"></i> <%= event.location %></p>
        <p class="card-text"><i class="far fa-clock pr-2"></i>
            <time datetime=<%= event.start_date %>
            <span class="day"> <%= event.start_date.day %> </span>
            <span class="month"> <%= event.start_date.strftime('%b') %> </span>
            <span class="year"> <%= event.start_date.year %> </span>
            <span class="time"> </span>
            </time>
        </p>
        </div>
    </div>
    <!-- Card image -->
    <div class="view overlay">
        <% if event.event_picture.attached? %>
            <%= image_tag event.event_picture, size: "350x350", alt: "Card image cap" %>
        <% end %>
    </div>
    <!-- Card content -->
    <div class="card-body">
        <div class="collapse-content">
        <!-- Text -->
        <%= h truncate(event.description, :length => 150) { link_to 'Voir plus', event_path(event.id), class:"link_to" } %>
        <!-- Button -->
        <i class="fas fa-share-alt text-muted float-right p-1 my-1" data-toggle="tooltip" data-placement="top" title="Share this post"></i>
        <i class="fas fa-heart text-muted float-right p-1 my-1 mr-3" data-toggle="tooltip" data-placement="top" title="I like it"></i>
        </div>
    </div>
    
</div>

app/views/shared/_card_offer.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="view overlay">
            <% if offer.offer_picture.attached? %>
                <%= image_tag offer.offer_picture, size: "350x350", alt: "Card image cap" %>
            <% end %>
        </div>
    </div>

    <div class="col-md-8">
        <div class="row">
            <%= link_to offer_path(id: offer.id), class:"link_to" do %>
                <h4 class="card-title font-weight-bold mb-2" style="text-transform: uppercase;"><%= offer.title %></h4>
            <% end %>
        </div>
        <div class="row text-align-right">
            <%= offer.category.title if offer.category %>
        </div>
        <div class="row">
            <%= offer.description %>
        </div>
    </div>
</div>

app/views/shared/_list_events.html.erb
<div class="row m-2 border-bottom">
    <div class="col-sm-3">
        <h5><%= event.title %></h5>
    </div>

    <div class="col-sm-3">
        <p><%= event.attendances.count %> <%= (event.attendances.count) == 1 ? 'Participant' : 'Participants'%></p>
    </div>

    <div class="col-sm-3">
        <p><%= event.start_date.strftime("%A, %d %B %Y") %></p>
    </div>

    <div class="col-sm-3">
        <%= button_to "Modifier l'évènement", edit_event_path(id: event.id), method: :get, class:"btn btn-success" %>
    </div>
</div>

app/views/shared/_list_forum.html.erb
<div class="row m-2 border-bottom" style="height:100px">
    <div class="col-sm-4 justify-content-center">
        <p><%= forum.title %></p>
    </div>

    <div class="col-sm-2 justify-content-center">
        <p>Nombre de post : <%= forum.forum_posts.count %></p>
    </div>

    <div class="col-sm-4">
    </div>

    <div class="col-sm-2 justify-content-center">
        <%= button_to "Modifier", edit_village_forum_path(@village, forum), method: :get, class:"btn btn-success" %>
    </div>
</div>

app/views/shared/_list_forums.html.erb
<div class="row m-2 border-bottom" style="height:100px">
    <div class="col-sm-4 justify-content-center">
        <p><%= forum.title %></p>
    </div>

    <div class="col-sm-2 justify-content-center">
        <p>Nombre de post : <%= forum.forum_posts.count %></p>
    </div>

    <div class="col-sm-4">
    </div>

    <div class="col-sm-2 justify-content-center">
        <%= button_to "Modifier", edit_village_forum_path(@village, forum), method: :get, class:"btn btn-success" %>
    </div>
</div>

app/views/shared/_list_offers.html.erb
<div class="row m-2 border-bottom" style="height:100px">
    <div class="col-sm-3 justify-content-center">
        <p><%= offer.title %></p>
    </div>

    <div class="col-sm-7 justify-content-center">
        <%= h truncate(offer.description, :length => 150) { link_to 'Voir plus', offer_path(offer.id), class:"link_to" } %>
    </div>

    <div class="col-sm-2 justify-content-center">
        <%= button_to "Modifier", edit_village_forum_path(@village, forum), method: :get, class:"btn btn-success" %>
    </div>
</div>

app/views/shared/_list_validation.html.erb
<div class="row m-2 border-bottom" style="height:100px">

    <div class="col-sm-1 justify-content-center">
        <% if validation.villager.villager_picture.attached? %>
            <%= image_tag(validation.villager.villager_picture, size: "60x60", class:"rounded") %>
        <% end %>
    </div>

    <div class="col-sm-2 justify-content-center">
        <p><%= validation.villager.first_name %> <%= validation.villager.last_name %></p>
    </div>

    <div class="col-sm-5 align-middle">
        <p><%= validation.message %></p>
    </div>

    <div class="col-sm-2 justify-content-center">
        <%= button_to "Valider", village_validation_town_halls_path(@village), method: :post, class:"btn btn-success", params: { villager_id: validation.villager.id } %>
    </div>

    <div class="col-sm-2 justify-content-center">
        <%= button_to "Refuser !", village_validation_town_hall_path(@village, validation.id), data: {confirm: "Voulez-vous refuser l'utilisateur ?" }, method: :delete, class:"btn btn-danger", params: { villager_id: validation.villager.id } %>
    </div>
</div>

app/views/shared/_post_villager.html.erb
<div class="row w-100 m-2 border">
    <div class="card w-100">
        <div class="card-header" style="height:100px">
            <%= image_tag(post.villager.villager_picture, size: "60x60", class:"rounded") %>
            <%= post.villager.first_name %> <%= post.villager.last_name %>
            
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= post.content %></h5>
            <div class="row">
                <div class="col-sm-6">
                    <footer class="blockquote-footer"> <%= post.created_at.strftime("%m/%d/%Y à %H:%M") %> </footer>
                </div>
                <div class="col-sm-6 align-item-center">

                        <% if user_signed_in? && post.villager = current_user.villager %>
                            <div class="row justify-content-end p-é">
                                <%= button_to "Modifier", edit_village_forum_forums_post_path(@village, @forum, post), method: :get, class:"btn btn-success mr-4" %>
                            </div>
                        <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-sm-12">

            <%= form_tag(offers_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
                <%= submit_tag "Search" %>
            <% end %>

            <%= form_tag(offers_search_path, method: :get, remote: true) do %>
                <div class="input-group mb-5">
                    <div class="row">
                        <%= text_field_tag :search, '', class:'form-control', placeholder:"Recherche..", onkeydown: 'clickSubmit()'%>
                    </div>
                </div>
                <div class="row">
                    <%= check_box_tag :title %> Title
                    <%= select_tag 'filter', options_for_select(['Reprendre un commerce', 'Immobilier', "Offre d'emploi"]), class:"custom-select" %>
                    <%= submit_tag "Search", class:'btn btn-dark', id: 'search_submit', style:"display:none" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<script>
    function clickSubmit() {
        $("#search_submit").trigger("click");
    }
</script>




    <div class="card">
        <article class="card-group-item">
            <header class="card-header">
                <h6 class="title">Brands </h6>
            </header>
            <div class="filter-content">
                <div class="card-body">
                <form>
                    <label class="form-check">
                    <input class="form-check-input" type="checkbox" value="">
                    <span class="form-check-label">
                        Mersedes Benz
                    </span>
                    </label> <!-- form-check.// -->
                    <label class="form-check">
                    <input class="form-check-input" type="checkbox" value="">
                    <span class="form-check-label">
                        Nissan Altima
                    </span>
                    </label>  <!-- form-check.// -->
                    <label class="form-check">
                    <input class="form-check-input" type="checkbox" value="">
                    <span class="form-check-label">
                        Another Brand
                    </span>
                    </label>  <!-- form-check.// -->
                </form>

                </div> <!-- card-body.// -->
            </div>
        </article> <!-- card-group-item.// -->
        
        <article class="card-group-item">
            <header class="card-header">
                <h6 class="title">Choose type </h6>
            </header>
            <div class="filter-content">
                <div class="card-body">
                <label class="form-check">
                <input class="form-check-input" type="radio" name="exampleRadio" value="">
                <span class="form-check-label">
                    First hand items
                </span>
                </label>
                <label class="form-check">
                <input class="form-check-input" type="radio" name="exampleRadio" value="">
                <span class="form-check-label">
                    Brand new items
                </span>
                </label>
                <label class="form-check">
                <input class="form-check-input" type="radio" name="exampleRadio" value="">
                <span class="form-check-label">
                    Some other option
                </span>
                </label>
                </div> <!-- card-body.// -->
            </div>

        </article> <!-- card-group-item.// -->
    </div> <!-- card.// -->

app/views/shared/_sidebar_forums.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-sm-12 align-items-start">
            <% @village.forums.all.each do |f| %>
                <div class="row align-item-center m-2" style="height:50px">
                    <%= link_to f.title, village_forum_path(@village, f), class:"link_to", style:"font-size:20px" %>
                </div>
            <% end %>
        </div>
    </div>
</div>