config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :town_halls, controllers: { sessions: 'town_halls/sessions', passwords: 'town_halls/passwords', registrations: 'town_halls/registrations', confirmations: 'town_halls/confirmations' }
  resources :manage_registration_town_halls, only: [:new, :create]
  resources :town_halls, only: [:show]
  
  root 'static_pages#welcome'
  get 'static_pages/contact', to: 'static_pages#contact'

  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :villagers, only: [:show, :edit, :update] do
    resources :associate_villagers, only: [:new, :create]

    resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
    end
  end

  resources :villages do
    resources :validation_town_halls, only: [:create, :destroy]
    resources :forums do
      resources :forums_posts do
        resources :forums_posts_comments, except: [:index, :show]
      end
    end
  end

  resources :events do
    resources :attendances, only: [:new, :show, :create, :destroy]
    resources :charges, only: [:new, :create]

    resources :comments do
      resources :likes
    end

  end

  resources :offers do
    get 'offers/search', to: 'offers#search'
    resources :offers_comments
  end

  resources :categories, except: [:index, :show]



end

app/controllers/offers_comments_controller.rb
class OffersCommentsController < ApplicationController
  before_action :find_offer
  before_action :find_comment, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_town_hall_or_user
  before_action :authenticate_author, except: [:new, :create, :index, :show]
  
  
  def index
   
  end

  def new
    @comment = OfferComment.new
  end

  def create
    
    @comment = OfferComment.new(comment_params)
    @comment.villager = current_user.villager
    @comment.offer = @offer
    

    if @comment.save
      redirect_to offer_path(@offer), notice: "Le commentaire a bien été créé"
    else
      redirect_to new_offer_offers_comment_path, alert: "Certaines informations sont incorrectes"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
        redirect_to offer_path(@offer), notice: "votre commentaire est bien modifié"
    else
        redirect_to edit_offer_offers_comment_path(@offer), alert: "Veuillez renseigner toutes les informations"
    end
  end

  def destroy
    @comment = OfferComment.find(params[:id])     
    @comment.destroy     
    redirect_to offer_path(@comment.offer_id), alert: "Le commentaire a bien été supprimé"
  end
  
  private
  
    def comment_params
        params.require(:offer_comment).permit(:content)
    end

    def find_comment
        @comment = OfferComment.find(params[:id])
    end

    def find_offer
      @offer = Offer.find(params[:offer_id])
    end

    def authenticate_town_hall_or_user
      redirect_to new_user_session_path, alert: "Veuillez vous connecter" if !user_signed_in? && !town_hall_signed_in?
    end

    def authenticate_author
      if user_signed_in?
        redirect_to root_path, alert: "Vous n'avez pas accès à cette page" if current_user.villager!= @comment.villager
      end
    end

end

app/helpers/offers_comments_helper.rb
module OffersCommentsHelper
end

app/views/offers_comments/create.html.erb
<h1>OffersComments#create</h1>
<p>Find me in app/views/offers_comments/create.html.erb</p>

app/views/offers_comments/edit.html.erb
<div class="container">
    <div class="row">
          <div class="col-md-6 offset-md-3">  
              <br><br><br>

               <%= form_for @comment, url: offer_offers_comment_path(@offer), method: :patch do |f| %>
                   <h1>Modifiez votre commentaire : </h1>
                   
                  <div class="form-group">
                      <%= f.label 'Renseignez vos modifications :'%>
                      <%= f.text_area :content, autofocus: true, autocomplete: "title", class: "form-control"%>
                  </div>

                  <div class="actions mt-5">       
                    <%= f.submit("Valider les modifications", class: "btn btn-lg btn-success btn-block") %>
                  </div> 

              <% end %>
              <div class="actions mt-2">       
                <%= button_to "Supprimer", offers_comments_path(params[:offer_id], params[:id]), data: {confirm: "Voulez-vous supprimer le commentaire ?" }, method: :delete, class:"btn btn-lg btn-danger btn-block" %>
              </div> 
          </div>
    </div>
</div>

app/views/offers_comments/index.html.erb
<h1>OffersComments#index</h1>
<p>Find me in app/views/offers_comments/index.html.erb</p>

app/views/offers_comments/new.html.erb
<div class="container">
    <div class="row">
          <div class="col-md-6 offset-md-3">  
              <br><br><br>

               <%= form_for @comment, url: offer_offers_comments_path(@offer) do |f| %>
                   <h1>Créez un commentaire pour cet évenement : </h1>
                   <p>remplissez le formulaire</p>


                  <div class="form-group">
                      <%= f.label 'Renseignez votre commentaire :'%>
                      <%= f.text_area :content, autofocus: true, autocomplete: "title", class: "form-control"%>
                  </div>

                  <div class="actions mt-5">       
                  <%= f.submit("Publier le commentaire", class: "btn btn-lg btn-success btn-block") %>
                  </div> 
                  <% end %>
          </div>
    </div>
</div>

app/views/offers_comments/show.html.erb
<h1>OffersComments#show</h1>
<p>Find me in app/views/offers_comments/show.html.erb</p>

app/views/offers_comments/update.html.erb
<h1>OffersComments#update</h1>
<p>Find me in app/views/offers_comments/update.html.erb</p>